name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: YAML Lint
        run: | 
          sudo apt-get update && sudo apt-get install -y yamllint
          yamllint k8s-manifests/

