name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run YAML Lint
        run: |
          yamllint k8s-manifests/

      - name: Deploy to Cluster
        run: |
          kubectl apply -f k8s-manifests/
